EVENT_START = "START"
EVENT_END = "END"
EVENT_MESSAGE = "MESSAGE"
EVENT_TRANSFER = "TRANSFER"

EVENT_START_LOG = f"\x1b[32m{EVENT_START}\x1b[0m"
EVENT_END_LOG = f"\x1b[31m{EVENT_END}\x1b[0m"
EVENT_MESSAGE_LOG = f"\x1b[33m{EVENT_MESSAGE}\x1b[0m"
EVENT_TRANSFER_LOG = f"\x1b[34m{EVENT_TRANSFER}\x1b[0m"
